---

- hosts: jenkins-slave
  become: true
  tasks:
  - name: updating the repo 
    apt:
      update_cache: true
      cache_valid_time: 3000
  - name: install java for slave
    apt:
      name: openjdk-17-jre
      state: present
  - name: Create a home directory for jenkins in slave
    file:
      path: /home/zain/jenkins
      state: directory
      mode: '0755'
      owner: zain
      group: zain